Repository FRONTENDSCHOOL6/WonT, pull requests merged in 2023-09, with the labels that each got.

#45 feat: ButtonLarge 컴포넌트 생성
  src/components/Button.jsx
  src/components/ButtonLarge.jsx
Labels: 💻 Feature

#46 style : tailwind.css - 스타일 추가
  src/styles/tailwind.css
Labels: 💻 HTML/CSS

#53 feat: My page 마크업 및 스타일링 진행 중
  src/assets/common-plain.svg
  src/components/BookMark.jsx
  src/components/Header/Header.jsx
  src/components/Map.jsx
  src/components/RootLayout.jsx
  src/components/mypage/Logout.jsx
  src/components/mypage/MyPageHeader.jsx
  src/components/mypage/MyPageTab.jsx
  src/components/mypage/PlanPreview.jsx
  src/components/mypage/Profile.jsx
  src/components/tripeditpage/AddPlan.jsx
  src/components/tripeditpage/ButtonMedium.jsx
  src/components/tripeditpage/TripPlan.jsx
  src/components/tripeditpage/TripPlaneIcon.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TripEditPage.jsx
  src/routes.jsx
  src/styles/tailwind.css
Labels: 💻 Feature

#54 [Landing page] 마크업 및 스타일링 완성
  src/App.jsx
  src/assets/LandingPage-bookmark.svg
  src/assets/LandingPage-calender.svg
  src/assets/LandingPage-plane.svg
  src/components/Footer.jsx
  src/components/Landing/LandingPagePartBottom.jsx
  src/components/Landing/LandingPagePartMiddle.jsx.jsx
  src/components/Landing/LandingPagePartTop.jsx
  src/components/Landing/SignUpButton.jsx
  src/components/Landing/SigninButton.jsx
  src/components/Landing/Sns.jsx
  src/components/Logo.jsx
  src/components/Sns.jsx
  src/pages/LandingPage.jsx
  src/routes.jsx
  tailwind.config.js
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#67 [TripLocal/TripCalendarPage] 작업
  package.json
  pnpm-lock.yaml
  src/assets/delete/common-arrow-left.svg
  src/assets/delete/common-close.svg
  src/components/CloseIcon.jsx
  src/components/Header/BackIcon.jsx
  src/components/Header/ButtonBack.jsx
  src/components/Header/TripHeader.jsx
  src/components/Header/UserIcon.jsx
  src/components/TripCalendar/TripCalendar.jsx
  src/components/TripLocal/ButtonSmall.jsx
  src/components/TripLocal/LocalItem.jsx
  src/components/TripTitle.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripLocalPage.jsx
  src/store/localStore.js
  src/styles/calendar.css
Labels: 💻 Feature, 💻 Fix, 💻 React

#70 [Landing page, SignInPage, SignUpPage] 마크업 및 스타일링 수정 , 기능 구현
  src/assets/common-check.svg
  src/assets/common-warning.svg
  src/components/Landing/CarouselDiv.jsx
  src/components/Landing/LandingPagePartFour.jsx
  src/components/Landing/LandingPagePartOne.jsx
  src/components/Landing/LandingPagePartThree.jsx
  src/components/Landing/LandingPagePartTwo.jsx
  src/components/Sign/FailModal.jsx
  src/components/Sign/SignInButton.jsx
  src/components/Sign/SignPart.jsx
  src/components/Sign/SuccessModal.jsx
  src/pages/LandingPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignInPage.jsx
  src/routes.jsx
  tailwind.config.js
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 🛠️ Refactor, 💻 React

#71 My Schedule / Bookmark 기능 구현
  src/assets/common-trip-default.jpg
  src/components/BookMark.jsx
  src/components/TripPlan.jsx
  src/components/mypage/BookmarkList.jsx
  src/components/mypage/MyPageHeader.jsx
  src/components/mypage/MyPageTab.jsx
  src/components/mypage/PlanPreview.jsx
  src/hooks/useRecommendsList.js
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TripEditPage.jsx
  src/utils/getDDay.js
  src/utils/getPocketHostImageURL.js
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#73 [Main page] - 마크업 및 스타일링 완성
  src/assets/LandingPage-bookmark.svg
  src/assets/MainPage-planeIcon.svg
  src/components/main/MainHeader.jsx
  src/components/main/MainMakePlan.jsx
  src/components/main/MainMoreButton.jsx
  src/components/main/MainPlace.jsx
  src/components/main/MainTitle.jsx
  src/components/main/MainTravels.jsx
  src/pages/LandingPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 💻 React

#72 [TripPage들] 비동기 통신 및 마크업, Zustand 활용한 기본 기능 구현
  src/App.jsx
  src/api/useSDKData.js
  src/assets/delete/common-hambuger.svg
  src/assets/delete/common-plus.svg
  src/components/ButtonLarge.jsx
  src/components/Map.jsx
  src/components/TripLocal/LocalItem.jsx
  src/components/TripPlan.jsx
  src/components/TripPlanEditButton.jsx
  src/components/TripSelect/AddButton.jsx
  src/components/TripSelect/AddPlaceItem.jsx
  src/components/TripSelect/HambugerButton.jsx
  src/components/TripSelect/HambugerIcon.jsx
  src/components/TripSelect/PlusIcon.jsx
  src/components/TripSelect/TripPlaceImage.jsx
  src/components/TripSelect/TripPlaceInfo.jsx
  src/components/TripSelect/TripPlaceItem.jsx
  src/components/TripSelect/TripPlanMenu.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripHotelPage.jsx
  src/pages/TripLocalPage.jsx
  src/pages/TripPlacePage.jsx
  src/routes.jsx
  src/store/localStore.js
  src/store/toggleTripMenuStore.js
  src/utils/createRecord.js
  src/utils/getLocalName.js
  src/utils/index.js
  tailwind.config.js
Labels: 💻 Feature, 💻 HTML/CSS, 🌏 Accessibility, 💻 React

#78 Main page 랜더링완성, 반응형 구현
  package.json
  pnpm-lock.yaml
  src/components/main/MainMakePlan.jsx
  src/components/main/MainPlace.jsx
  src/components/main/MainTravels.jsx
  src/pages/LandingPage.jsx
  src/pages/MainPage.jsx
  src/routes.jsx
  src/utils/getPocketHostURL.js
Labels: 💻 Feature, 💻 HTML/CSS, 🛠️ Refactor, 💻 React

#80 [MySchedule/Bookmark/Detail] 페이지 기능 구현 및 마크업
  src/assets/detail-calendar.svg
  src/assets/detail-clock.svg
  src/assets/detail-homepage.svg
  src/assets/detail-info.svg
  src/assets/detail-ticket.svg
  src/components/BookMark.jsx
  src/components/Detail/DetailInfo.jsx
  src/components/Header/Header.jsx
  src/components/PageHeader.jsx
  src/components/TripEdit/AddPlan.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/mypage/BookmarkList.jsx
  src/components/mypage/Logout.jsx
  src/components/mypage/MyPageHeader.jsx
  src/components/mypage/MyPageTab.jsx
  src/components/mypage/PlanPreview.jsx
  src/components/mypage/Profile.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TripEditPage.jsx
  src/routes.jsx
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#79 TripCalendarPage - 여행 기간 선택 및 유틸함수 생성 작업 중
  src/components/TripCalendar/TripCalendar.jsx
  src/components/TripTitle.jsx
  src/pages/TripCalendarPage.jsx
  src/styles/calendar.css
  src/utils/getTripDate.js
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#84 feat. Trip calendar page - 접근성 및 store 생성
  src/components/MyScheduleDetail/TotalScheduleSummary.jsx
  src/components/MyScheduleDetail/TotalScheduleViewTitle.jsx
  src/components/TripCalendar/TripCalendar.jsx
  src/pages/MyScheduleDetailPage.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripLocalPage.jsx
  src/store/dateStore.js
  src/styles/calendar.css
  src/utils/getTripDate.js
  src/utils/getTripDays.js
  src/utils/index.js
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#85 [SignInPage] 기능 구현 완료
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/Sign/FailModal.jsx
  src/components/Sign/SignInButton.jsx
  src/components/Sign/SignPart.jsx
  src/contexts/Auth.jsx
  src/hooks/useStorage.js
  src/main.jsx
  src/pages/LandingPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 🛠️ Refactor, ⚙ Setting, 💻 React

#88 feat. Trip place hotel page - 선택 지역 마커 및 기능 추가
  index.html
  src/api/map.js
  src/components/Map.jsx
  src/components/MapSearch.jsx
  src/pages/TripHotelPage.jsx
  src/pages/TripPlacePage.jsx
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#89 MySchedule/Bookmark/Detail/Travels
  src/assets/detail-info.svg
  src/components/BookMark.jsx
  src/components/Detail/DetailInfo.jsx
  src/components/Header/BackIcon.jsx
  src/components/Logo.jsx
  src/components/Map.jsx
  src/components/PageHeader.jsx
  src/components/TripPlan.jsx
  src/components/mypage/BookmarkList.jsx
  src/components/mypage/MyPageTab.jsx
  src/components/mypage/PlanPreview.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TravelsPage.jsx
  src/routes.jsx
  src/store/memoStore.js
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#91 [SignUpPage] 기능 구현
  src/components/Logo.jsx
  src/components/Sign/SignPart.jsx
  src/components/main/MainHeader.jsx
  src/components/main/MainPlace.jsx
  src/components/main/MainTravels.jsx
  src/main.jsx
  src/pages/MainPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 React

#94 bug: src 경로 문제 수정
  src/components/mypage/BookmarkList.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
Labels: 💻 Fix

#95 [fix] MainPage 경로 변경
  src/components/main/MainHeader.jsx
  src/components/main/MainPlace.jsx
  src/components/main/MainTravels.jsx
  src/pages/MainPage.jsx
Labels: 💻 Fix, 💻 React

#96 feat : routes설정 및 bookmark 기능 구현 진행중
  src/components/PageHeader.jsx
  src/components/mypage/BookmarkList.jsx
  src/components/mypage/PlanPreview.jsx
  src/pages/DetailPage.jsx
  src/pages/TripEditPage.jsx
  src/routes.jsx
Labels: 💻 Feature, 💻 HTML/CSS, 💻 React

#97 feat : routes 이슈 수정
  src/pages/DetailPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 React

#98 fix. 컴포넌트, import 경로 수정 및 최적화
  index.html
  src/components/Main/MainHeader.jsx
  src/components/Main/MainMakePlan.jsx
  src/components/Main/MainMoreButton.jsx
  src/components/Main/MainPlace.jsx
  src/components/Main/MainTitle.jsx
  src/components/Main/MainTravels.jsx
  src/components/MyPage/BookmarkList.jsx
  src/components/MyPage/Logout.jsx
  src/components/MyPage/MyPageTab.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/MyPage/Profile.jsx
  src/pages/TripPlacePage.jsx
  src/routes.jsx
  vercel.json
Labels: 💻 Fix, 🌏 Accessibility

#101 feat. MyScheduleDetail Page - 클릭한 북마크 정보만 필터링
  src/pages/MyScheduleDetailPage.jsx
Labels: 💻 Fix, 💻 React

#103 fix: 폰트 최적화
  index.html
  src/components/MapCategory.jsx
  src/components/MapSearch.jsx
Labels: 🛠️ Refactor, 💻 React

#102 [Detail | Bookmark | MySchedule] 북마크 기능구현 및 렌더링
  index.html
  src/components/Detail/DetailInfo.jsx
  src/components/MyPage/BookmarkList.jsx
  src/components/MyPage/MyPageTab.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/TripEdit/PlanDate.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
Labels: 💻 Feature, 💻 Fix, 💻 React

#104 rename: 사용하지 않는 assets 정리
  src/assets/common-arrow-down.svg
  src/assets/common-arrow-right.svg
  src/assets/common-arrow-up.svg
  src/assets/common-default-image.svg
  src/assets/common-map.svg
  src/assets/common-paperplane-primary.svg
  src/assets/common-paperplane-secondary.svg
  src/assets/common-search.svg
  src/assets/common-toogle-left.svg
  src/assets/common-toogle-right.svg
  src/assets/delete/common-arrow-left.svg
  src/assets/delete/common-close.svg
  src/assets/delete/common-hambuger.svg
  src/assets/delete/common-logo.svg
  src/assets/delete/common-plus.svg
  src/assets/delete/miram-oh-sNxmBz_aJ_k-unsplash.jpg
  src/components/FormInput.jsx
Labels: ✨ Deploy, 💻 React

#106 Map API 원하는 지역 내 카테고리 출력 기능 구현
  src/components/MapSearch.jsx
  src/store/mapStore.js
Labels: 💻 React

#107 fix: Map 작업 위한 수정사항 반
  src/components/MapSearch.jsx
  src/pages/TripCalendarPage.jsx
Labels: 💻 React

#108 [All Page] 확장자 수정, 불필요한 jsx 페이지 삭제
  src/components/Detail/DetailInfo.jsx
  src/components/Main/MainPlace.jsx
  src/components/Main/MainTravels.jsx
  src/components/Map.jsx
  src/components/MyPage/MyPageTab.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/MyScheduleDetail/TotalScheduleSummary.jsx
  src/components/PageHeader.jsx
  src/components/Sign/SuccessModal.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/TripPlan.jsx
  src/pages/LandingPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/MyScheduleDetailPage.jsx
  src/pages/SearchPage.jsx
  src/pages/SignInPage.jsx
  src/pages/TravelsPage.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripEditPage.jsx
  src/pages/TripLocalPage.jsx
Labels: 💻 Fix, 🛠️ Refactor, ✨ Deploy, 💻 React

#111 [Landing page] 성능 최적화 완료
  src/assets/LandingPage-bookmark.webp
  src/assets/LandingPage-calender.webp
  src/assets/LandingPage-gallery.webp
  src/components/Landing/CarouselDiv.jsx
  src/components/Landing/LandingPagePartFour.jsx
  src/components/Landing/LandingPagePartOne.jsx
  src/components/Landing/LandingPagePartThree.jsx
  src/components/Landing/LandingPagePartTwo.jsx
  src/components/Landing/Sns.jsx
  src/components/Logo.jsx
Labels: 💻 Fix, 🛠️ Refactor, 🌏 Accessibility

#112 feat: 카테고리 검색 작업 완료 및 호텔 검색 작업 중
  src/components/MapCategory.jsx
  src/components/TripSelect/MapHotel.jsx
  src/components/TripSelect/MapSearch.jsx
  src/pages/TripHotelPage.jsx
  src/pages/TripPlacePage.jsx
  src/store/mapStore.js
Labels: 💻 Feature, 💻 React

#115 [Detail | MyShedule | Bookmark] 기능구현 및 스타일 수정
  src/components/Map.jsx
  src/components/MyPage/BookmarkList.jsx
  src/components/MyPage/MyPageTab.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/PageHeader.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/store/bookmarkStore.js
  tailwind.config.js
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 💻 React

#117 feat. 실시간 지도 위치 렌더링
  src/components/TripSelect/MapHotel.jsx
  src/components/TripSelect/MapPlace.jsx
  src/components/TripSelect/TripPlaceInfo.jsx
  src/components/TripSelect/TripPlaceItem.jsx
  src/pages/TripHotelPage.jsx
  src/store/mapStore.js
Labels: 💻 Feature, 💻 React

#118 [Landing page] 성능개선 , 반응형 개선
  src/assets/LandingPage-carousel-four.webp
  src/assets/LandingPage-carousel-one.webp
  src/assets/LandingPage-carousel-six.webp
  src/assets/LandingPage-carousel-three.webp
  src/components/Landing/CarouselDiv.jsx
  src/components/Landing/LandingPagePartFour.jsx
  src/components/Landing/LandingPagePartOne.jsx
  src/components/Landing/LandingPagePartThree.jsx
  src/components/Landing/LandingPagePartTwo.jsx
  src/components/Landing/Sns.jsx
Labels: 💻 Fix, 💻 HTML/CSS, 🛠️ Refactor, 💻 React

#119 [MySchedule | Bookmark | Travels] 애니메이션 수정 및 반응형 깨짐 수정
  src/components/MyPage/BookmarkList.jsx
  src/components/MyPage/MyPageTab.jsx
  src/components/MyPage/MyPageTabInfo.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/PageHeader.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TravelsPage.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 💻 React

#120 [Main page] 기능추가 및 반응형 조절
  src/components/Main/MainPlace.jsx
Labels: 💻 Feature, 💻 Fix, 🛠️ Refactor, 💻 React

#122 bug: 반영된 위치 마커만 화면에 출력
  src/components/TripSelect/MapHotel.jsx
  src/pages/TripHotelPage.jsx
  src/store/mapStore.js
Labels: 💻 Fix, 💻 React

#123 [Main page] 북마크 버튼 기능 구현
  src/components/Main/MainPlace.jsx
  src/store/bookmarkStore.js
Labels: 💻 Feature, 💻 Fix, 💻 HTML/CSS, 💻 React

#124 [Common | TripEdit] favicon 추가 및 지도 데이터 렌더링 진행 중
  index.html
  src/assets/common-favicon.svg
  src/components/Map.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/TripEdit/ScheduleMap.jsx
  src/components/TripPlan.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TripEditPage.jsx
  src/styles/tailwind.css
  tailwind.config.js
Labels: 💻 Common, 💻 Feature, 💻 React

#125 [Main page] 북마크 상태 제어 추가
  src/App.jsx
  src/components/Main/MainPlace.jsx
  src/components/Main/MainTravels.jsx
  src/components/MyPage/BookmarkList.jsx
  src/pages/DetailPage.jsx
  src/pages/LandingPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignInPage.jsx
  src/pages/SignUpPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 React

#126 [TripEdit] 선택한 여행 정보 데이터 렌더링 진행중
  src/App.jsx
  src/components/Main/MainMakePlan.jsx
  src/components/Map.jsx
  src/components/MyPage/PlanPreview.jsx
  src/components/PageHeader.jsx
  src/components/TripPlan.jsx
  src/pages/DetailPage.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TravelsPage.jsx
  src/pages/TripEditPage.jsx
  tailwind.config.js
Labels: 💻 Feature, 💻 Fix, 💻 React

#135 feat, fix: 지역 선택 후 취소 기능 구현 및 최적화
  src/components/TripLocal/LocalImage.jsx
  src/components/TripLocal/LocalItem.jsx
  src/pages/TripLocalPage.jsx
Labels: 💻 Fix, ✨ Deploy, 💻 React

#136 fix: 리렌더링 방지 및 적절한 여백 주기
  src/components/TripCalendar/TripCalendar.jsx
  src/pages/TripCalendarPage.jsx
Labels: 💻 Fix

#137 [TripEdit] 저장된 마커 지도에 표시 및 일정 정보렌더링
  src/components/Map.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/TripEdit/SelectHotelMap.jsx
  src/components/TripEdit/TripSchedule.jsx
  src/components/TripPlan.jsx
  src/pages/TripEditPage.jsx
  src/store/markerStore.js
  src/store/selectRangeStore.js
  src/utils/getRangeDay.js
  tailwind.config.js
Labels: 💻 Feature, 💻 React

#138 feat: TripHotelPage - 숙소 선택 및 추가 항목 렌더링
  src/components/TripSelect/AddButton.jsx
  src/components/TripSelect/AddPlaceItem.jsx
  src/components/TripSelect/AddPlaceItemContent.jsx
  src/components/TripSelect/CheckIcon.jsx
  src/components/TripSelect/TripPlaceItem.jsx
  src/pages/TripHotelPage.jsx
  src/store/mapStore.js
  src/store/scheduleStore.js
Labels: 💻 Feature, 🪄 Test, 💻 React

#140 fix: 변경사항 재반영
  src/components/TripCalendar/TripCalendar.jsx
  src/pages/TripCalendarPage.jsx
Labels: 💻 Fix

#141 feact. MyScheduleDetailPage 렌더링
  src/components/Modal.jsx
  src/components/MyScheduleDetail/TotalScheduleSummary.jsx
  src/components/MyScheduleDetail/TotalScheduleView.jsx
  src/components/MyScheduleDetail/TotalScheduleViewHotelDay.jsx
  src/components/MyScheduleDetail/TotalScheduleViewImageList.jsx
  src/components/MyScheduleDetail/TotalScheduleViewTitle.jsx
  src/components/MyScheduleDetail/TotalScheduleViewTopic.jsx
  src/pages/MyScheduleDetailPage.jsx
  src/utils/getPocketHostImageURL.js
Labels: 💻 React

#142 Map & Select Page flow 작업 완료
  src/components/MyScheduleDetail/TotalScheduleView.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/TripPlan.jsx
  src/components/TripSelect/AddButton.jsx
  src/components/TripSelect/TripPlaceItem.jsx
  src/pages/MyScheduleDetailPage.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripEditPage.jsx
  src/pages/TripHotelPage.jsx
  src/pages/TripLocalPage.jsx
  src/routes.jsx
  src/store/scheduleStore.js
  src/utils/getTripDate.js
  src/utils/index.js
  src/utils/updateRecord.js
Labels: 💻 Feature

#145 [TripEdit] 데이터 렌더링 및 업데이트 진행중
  src/components/PageHeader.jsx
  src/components/TripEdit/PlacePlan.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/TripEdit/SelectHotelMap.jsx
  src/components/TripPlan.jsx
  src/pages/DetailPage.jsx
  src/pages/TripEditPage.jsx
  src/pages/TripHotelPage.jsx
Labels: 💻 Feature, 💻 Fix, 💻 React

#146 [docs] readme 추가
  README.md
Labels: 📑 Docs

#148 [docs] readme 완료
  README.md
Labels: 📑 Docs

#149 feat. Map API - infowindow 커스텀
  src/components/TripSelect/MapHotel.jsx
  src/components/TripSelect/MapPlace.jsx
  src/pages/TripHotelPage.jsx
Labels: 💻 Feature, 💻 React

#150 feat: Trip schedule detail page - 렌더링 에러 해결 및 기능 구현
  src/components/MyScheduleDetail/DayScheduleItem.jsx
  src/components/MyScheduleDetail/TotalScheduleView.jsx
  src/components/MyScheduleDetail/TotalScheduleViewHotelDay.jsx
  src/pages/MyScheduleDetailPage.jsx
Labels: 💻 Fix, 💻 React

#151 [TripEdit] 버튼을 통한 데이터 업데이트 및 삭제 구현 진행중
  src/components/TripEdit/ButtonMedium.jsx
  src/components/TripEdit/PlacePlan.jsx
  src/components/TripEdit/PlanDate.jsx
  src/components/TripEdit/SelectHotelMap.jsx
  src/pages/TripEditPage.jsx
  src/pages/TripPlacePage.jsx
  src/store/scheduleStore.js
  src/store/tripScheduleStore.js
Labels: 💻 Feature, 💻 React
