Repository FRONTENDSCHOOL6/WonT, pull requests merged in 2024-01, with the labels that each got.

#161 Ts/landing - 마이그레이션
  src/components/Footer.tsx
  src/components/Landing/CarouselDiv.tsx
  src/components/Landing/LandingSectionFour.tsx
  src/components/Landing/LandingSectionOne.tsx
  src/components/Landing/LandingSectionThree.tsx
  src/components/Landing/LandingSectionTwo.tsx
  src/components/Landing/Sns.tsx
  src/components/Logo.tsx
  src/pages/LandingPage.tsx
  tsconfig.json
Labels: 🛠️ Refactor

#165 Ts/sign - 마이그레이션
  src/components/Sign/BackButton.tsx
  src/components/Sign/SignInButton.tsx
  src/components/Sign/SignPart.jsx
  src/components/Sign/SignPart.tsx
  src/components/Sign/SignUpButton.tsx
  src/contexts/Auth.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
Labels: 🛠️ Refactor

#175 Refactor : TripEditPage의 Components Type 설정
  src/components/MyPage/PlanPreview.jsx
  src/components/TripEdit/AddPlan.tsx
  src/components/TripEdit/ButtonMedium.tsx
  src/components/TripEdit/PlacePlan.tsx
  src/components/TripEdit/PlanDate.tsx
  src/components/TripEdit/ScheduleMap.tsx
  src/components/TripEdit/SelectHotelMap.tsx
  src/components/TripEdit/TripPlaneIcon.tsx
  src/components/TripEdit/TripSchedule.tsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TripEditPage.tsx
Labels: 💻 Fix, 🛠️ Refactor

#178 Ts/common: 유틸함수 JS -> TS 리팩토링 작업
  package.json
  pnpm-lock.yaml
  src/components/Main/MainPlace.tsx
  src/components/Main/MainTravels.tsx
  src/components/MyPage/PlanPreview.jsx
  src/components/MyScheduleDetail/TotalScheduleSummary.jsx
  src/components/MyScheduleDetail/TotalScheduleViewTitle.jsx
  src/components/TripCalendar/TripCalendar.jsx
  src/pages/MyPage/BookmarkPage.jsx
  src/pages/MyPage/MySchedule.jsx
  src/pages/TravelsPage.jsx
  src/pages/TripCalendarPage.jsx
  src/pages/TripLocalPage.jsx
  src/utils/createRecord.js
  src/utils/createRecord.ts
  src/utils/debounce.js
  src/utils/debounce.ts
  src/utils/encoding.js
  src/utils/encoding.ts
  src/utils/getDDay.ts
  src/utils/getLocalName.js
  src/utils/getLocalName.ts
  src/utils/getNode.js
  src/utils/getNode.ts
  src/utils/getPocketHostURL.ts
  src/utils/getRangeDay.ts
  src/utils/getTripDate.js
  src/utils/getTripDate.ts
  src/utils/index.js
  src/utils/index.ts
  src/utils/propTypes.js
  src/utils/updateRecord.js
  src/utils/updateRecord.ts
Labels: 🛠️ Refactor

#182 Refactor : Detail 페이지의 Components type 지정
  src/App.tsx
  src/components/Detail/DetailInfo.tsx
  src/components/Map.jsx
  src/components/TripEdit/ButtonMedium.tsx
  src/components/TripEdit/PlacePlan.tsx
  src/components/TripEdit/PlanDate.tsx
  src/components/TripEdit/ScheduleMap.tsx
  src/components/TripEdit/SelectHotelMap.tsx
  src/components/TripEdit/TripSchedule.tsx
  src/pages/DetailPage.tsx
  src/pages/TripEditPage.tsx
  src/types/TripEdit.ts
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript

#184 Refactor : Travels | MyScheduleDetailPage 페이지의 Components type 지정
  src/components/ButtonLarge.tsx
  src/components/Detail/DetailInfo.tsx
  src/components/Map.tsx
  src/components/MyScheduleDetail/DayScheduleItem.tsx
  src/components/MyScheduleDetail/ToggleTotalSchedule.tsx
  src/components/MyScheduleDetail/TotalScheduleSummary.tsx
  src/components/MyScheduleDetail/TotalScheduleView.tsx
  src/components/MyScheduleDetail/TotalScheduleViewHotelDay.tsx
  src/components/MyScheduleDetail/TotalScheduleViewImageList.tsx
  src/components/MyScheduleDetail/TotalScheduleViewTitle.tsx
  src/components/MyScheduleDetail/TotalScheduleViewTopic.tsx
  src/components/TripEdit/ScheduleMap.tsx
  src/pages/DetailPage.tsx
  src/pages/MyScheduleDetailPage.tsx
  src/pages/TravelsPage.tsx
  src/pages/TripEditPage.tsx
  src/store/toggleTripMenuStore.js
  src/store/toggleTripMenuStore.ts
  src/types/Locals.ts
  src/types/MyScheduleDetailPage.ts
  src/types/Travels.ts
  src/types/TripEdit.ts
  src/utils/getPocketHostImageURL.js
  src/utils/getPocketHostImageURL.ts
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript

#187 Feature/common : 마이그레이션으로 인한 리팩토링
  src/components/CloseIcon.tsx
  src/components/DefaultImage.tsx
  src/components/DeleteButton.tsx
  src/components/LocationIcon.tsx
  src/components/Modal.tsx
  src/components/PageHeader.tsx
  src/components/ProtectRoute.tsx
  src/components/Spinner/Spinner.tsx
  src/components/ToggleDownIcon.tsx
  src/components/ToggleUpIcon.tsx
  src/components/TripPlan.tsx
  src/components/TripPlanEditButton.tsx
  src/components/TripTitle.tsx
  src/pages/MyScheduleDetailPage.tsx
  src/pages/RootLayout.tsx
  src/store/createStore.js
  src/types/Recommens.ts
  src/types/Travels.ts
Labels: 🧰 Refactor

#190 Refactor : MyPage Components type 지정 및 일부 Zustand Store 파일 타입 설정
  src/components/Main/MainPlace.tsx
  src/components/Map.tsx
  src/components/MyPage/BookmarkList.tsx
  src/components/MyPage/Logout.tsx
  src/components/MyPage/MyPageTab.tsx
  src/components/MyPage/MyPageTabInfo.tsx
  src/components/MyPage/PlanPreview.tsx
  src/components/MyPage/Profile.tsx
  src/components/MyScheduleDetail/TotalScheduleView.tsx
  src/components/MyScheduleDetail/TotalScheduleViewTopic.tsx
  src/components/TripCalendar/TripCalendar.tsx
  src/components/TripEdit/PlacePlan.tsx
  src/components/TripSelect/AddPlaceItemContent.jsx
  src/components/TripSelect/HambugerButton.jsx
  src/components/TripSelect/MapPlace.jsx
  src/components/TripSelect/TripPlaceItem.jsx
  src/pages/DetailPage.tsx
  src/pages/MyPage/BookmarkPage.tsx
  src/pages/MyPage/MySchedule.tsx
  src/pages/MyScheduleDetailPage.tsx
  src/pages/TravelsPage.tsx
  src/pages/TripCalendarPage.tsx
  src/pages/TripEditPage.tsx
  src/pages/TripHotelPage.jsx
  src/pages/TripPlacePage.jsx
  src/store/bookmarkStore.js
  src/store/bookmarkStore.ts
  src/store/buttonStore.js
  src/store/buttonStore.ts
  src/store/mapStore.js
  src/store/mapStore.ts
  src/store/memoStore.js
  src/store/memoStore.ts
  src/store/toggleTripMenuStore.ts
  src/store/tripScheduleStore.ts
  src/types/BookmarkPage.ts
  src/types/MySchedule.ts
  src/types/MyScheduleDetailPage.ts
  src/types/Travels.ts
  src/types/TripEdit.ts
  src/utils/getPocketHostImageURL.ts
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript, 🐻‍❄️ Zustand

#191 Ts/tripplace: 숙소, 여행 놀거리 선택 페이지 컴포넌트 JS -> TS 작업
  src/components/TripSelect/AddButton.tsx
  src/components/TripSelect/AddPlaceItem.jsx
  src/components/TripSelect/AddPlaceItem.tsx
  src/components/TripSelect/AddPlaceItemContent.tsx
  src/components/TripSelect/CheckIcon.tsx
  src/components/TripSelect/HambugerButton.tsx
  src/components/TripSelect/HambugerIcon.tsx
  src/components/TripSelect/PlusIcon.tsx
  src/components/TripSelect/TripHotelItem.tsx
  src/components/TripSelect/TripPlaceImage.tsx
  src/components/TripSelect/TripPlaceInfo.tsx
  src/components/TripSelect/TripPlaceItem.tsx
  src/components/TripSelect/TripPlanMenu.tsx
  src/pages/TripHotelPage.tsx
  src/pages/TripPlacePage.tsx
Labels: 🧰 Refactor, 👨‍💻 Typescript

#192 refactor : dateStore 코드 수정 및 적용
  src/components/TripPlan.tsx
  src/pages/TripEditPage.tsx
  src/store/dateStore.ts
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript, 🐻‍❄️ Zustand

#194 Ts/triphotelplace: 여행지 놀거리, 숙소 선택 페이지
  src/assets/trip/check.svg
  src/assets/trip/plus.svg
  src/components/TripSelect/AddButton.tsx
  src/components/TripSelect/HambugerButton.tsx
  src/components/TripSelect/MapHotel.tsx
  src/components/TripSelect/MapPlace.tsx
  src/components/TripSelect/TripHotelItem.tsx
  src/components/TripSelect/TripPlaceItem.tsx
  src/components/TripSelect/TripPlanMenu.tsx
  src/pages/TripHotelPage.tsx
  src/pages/TripLocalPage.tsx
  src/pages/TripPlacePage.tsx
  src/types/Recommends.ts
  src/utils/debounce.ts
  src/utils/getPocketHostImageURL.ts
Labels: 🧰 Refactor, 👨‍💻 Typescript

#197 Ts/common: 공통 사항 작업
  README.md
  index.html
  src/components/MyScheduleDetail/DayScheduleItem.tsx
  src/components/MyScheduleDetail/TotalScheduleView.tsx
  src/components/MyScheduleDetail/TotalScheduleViewHotelDay.tsx
  src/components/MyScheduleDetail/TotalScheduleViewTitle.tsx
  src/components/MyScheduleDetail/TotalScheduleViewTopic.tsx
  src/components/TripEdit/PlanDate.tsx
  src/components/TripLocal/LocalItem.tsx
  src/components/TripSelect/AddButton.tsx
  src/components/TripSelect/TripHotelItem.tsx
  src/components/TripSelect/TripPlaceItem.tsx
  src/contexts/Auth.tsx
  src/hooks/useFetchMySchedule.ts
  src/hooks/useStorage.ts
  src/main.tsx
  src/pages/TripEditPage.tsx
  src/pages/TripHotelPage.tsx
  src/pages/TripLocalPage.tsx
  src/pages/TripPlacePage.tsx
  src/store/dateStore.ts
  src/store/localStore.js
  src/store/localStore.ts
  src/store/markerStore.ts
  src/store/scheduleStore.js
  src/store/scheduleStore.ts
  src/store/selectRangeStore.js
  src/types/Locals.ts
  src/types/MyScheduleDetailPage.ts
  tailwind.config.js
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript

#198 fix: 경로명 수정
  index.html
  src/components/Landing/Sns.tsx
  src/components/Main/MainMakePlan.tsx
  src/components/MyPage/PlanPreview.tsx
  src/components/MyScheduleDetail/TotalScheduleSummary.tsx
  src/components/TripEdit/PlanDate.tsx
Labels: 💻 Fix

#199 fix : 이미지 렌더링 오류 및 타입 오류 해결
  src/components/Detail/DetailInfo.tsx
  src/components/MyPage/BookmarkList.tsx
  src/components/MyPage/PlanPreview.tsx
  src/pages/DetailPage.tsx
  src/pages/MyPage/MySchedule.tsx
  src/pages/TravelsPage.tsx
  src/types/DetailPage.ts
  src/types/MySchedule.ts
  src/types/Travels.ts
  src/utils/getPocketHostImageURL.ts
Labels: 💻 Fix, 🧰 Refactor, 👨‍💻 Typescript

#200 bug: 여행 날짜 선택 페이지 - 날짜 주석 처리
  src/components/TripCalendar/TripCalendar.tsx
  src/pages/TripCalendarPage.tsx
Labels: 🚨 SOS, 👨‍💻 Typescript

#207 Ts/MyScheduleDetail: 타입 에러 해결 및 임시 주석 처리
  src/components/MyScheduleDetail/TotalScheduleViewImageList.tsx
  src/components/TripSelect/TripPlanMenu.tsx
  src/pages/MyScheduleDetailPage.tsx
Labels: 💻 Fix, 🚨Bug, 👨‍💻 Typescript

#211 Ts/mypage
  src/components/TripCalendar/TripCalendar.tsx
  src/components/TripEdit/SelectHotelMap.tsx
  src/pages/MyPage/BookmarkPage.tsx
  src/pages/TripCalendarPage.tsx
  src/pages/TripEditPage.tsx
  src/store/scheduleStore.ts
  src/utils/getTripDate.ts
Labels: 💻 Fix, 🚨Bug, 🧰 Refactor, 👨‍💻 Typescript

#212 Ts/API:
  src/components/TripCalendar/TripCalendar.tsx
  src/pages/TripCalendarPage.tsx
  src/pages/TripLocalPage.tsx
  src/types/Locals.ts
  src/utils/createRecord.ts
Labels: 🧰 Refactor, 🪪 API, 👨‍💻 Typescript
